### ISSUE TITLE
Log is always showing that there is a newer version available

### ISSUE THREAD

**Issue by Apipa169** [greghesp/assistant-relay#137]
**Describe the bug**
When Assistant Relay is starting the log is showing that there is a newer version available, even if you are running the latest release.

**To Reproduce**
1. Start Assistant Relay
2. Look at the logs

**Expected behavior**
Only showing this message when you are running an older version.

**Screenshots**
I did not make a screenshot, but the text is: "0|www  | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases"

**Desktop (please complete the following information):**
-  Hass.io add-on on Intel NUC and RaspberryPi (docker)
 - Version v3.1.0 (and older)

**Comment by greghesp** [comment]
This should be fixed now
https://github.com/greghesp/assistant-relay/releases/tag/v3.1.1

**Comment by Apipa169** [comment]
It is still showing while I'm running the newest release. 

But maybe this is caused by the typo in the release tag "v.3.0.2" (dot between v and 3)

**Comment by greghesp** [comment]
One of those days 😂
Restart AR and it should be fixed

**Comment by Apipa169** [comment]
Haha, correct! Message is gone now.
