### ISSUE TITLE
Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by HeedfulCrayon** [greghesp/assistant-relay#222]
**Describe the bug**
Assistan relay seems to lose auth after a while.  Whenever testing anything in sandbox I get this error:
Getting metadata from plugin failed with error: invalid_grant

**To Reproduce**
Try any command in sandbox

**Expected behavior**
Command or broadcast to occur without issue.

**Desktop (please complete the following information):**
-  Platform Pi 4 running home assistant
 - Browser vivaldi
 - Version latest

**Comment by jayhohoho2019** [comment]
I just got exactly the same issue.  its been working for about a week.  I had to create another user using the same OAuth client ID.  why is that?

**Comment by jesselumarie** [comment]
Also seeing this issue

**Comment by littlbee** [comment]
Same issue, and also solved by creating a new user using the same credentials.

**Comment by HeedfulCrayon** [comment]
Creating a new user only fixes it temporarily.  After a few days it will go back to doing the same thing

**Comment by jesselumarie** [comment]
Yep that’s what I ran into

**Comment by matt---4** [comment]
Also getting this, going to try running a command to ask the time every six hours to see if that stops any timeout.

**Comment by jayhohoho2019** [comment]
Happening to me again, 7 days after.  Who is causing this to expire? GAR or Google?

**Comment by thomasbonte** [comment]
Same for me. @matt---4 Any luck with your testing to repeat a command every X hours?

**Comment by matt---4** [comment]
So far the issue hasn't happened since I started asking the time every six hours. I'll post back on here in a week or so with another update or if the issue happens again.

**Comment by thomasbonte** [comment]
@matt---4 ok good to know! I'll be testing this myself as well.

**Comment by Snacker001** [comment]
I'm having the same issue and have automations which run daily at minimum firing commands. All working fine until 2 days ago with nothing having changed but now with the invalid_grant error. Same happens if I fire from sandbox mode

**Comment by abdalians** [comment]
me 3

**Comment by littlbee** [comment]
I'm a bit concerned the dev doesn't seem to react on this issue... Is there anyone still maintaining this code ?

**Comment by HeedfulCrayon** [comment]
> I'm a bit concerned the dev doesn't seem to react on this issue... Is there anyone still maintaining this code ?

Calm down, last commit was 14 days ago.  Just set up an automation to run every 6 hours like stated above and you won't lose auth.  Mines been working fine for over a week

**Comment by Snacker001** [comment]
Not sure the regular automation trick works. I set up a new user to prevent the problem on the current user, set up an automation to run every 5 hours. It was fine for the first day and now is failing with the invalid_grant error again

**Comment by matt---4** [comment]
My raspberry pi crashed and I got invalid grant when it started up again. So I don't know how long the automation thing would have worked for.

**Comment by matteskonto** [comment]
Both my users lost the grant at the same time, one was used much more frequently than the other so I doubt it is interaction dependent

**Comment by HeedfulCrayon** [comment]
Just saying, mine is still going just fine

**Comment by Snacker001** [comment]
@HeedfulCrayon that's good. What environment are you using this in? For me I am using the Home Assistant add-on and triggering automations through node-red. Curiously at the moment I get the error only in node-red, but can still successfully use the sandbox mode to trigger directly on the latest user account. My original user account fails in both Node-red and sandbox.

I might try installing a separate instance on a VM and see how that goes.

**Comment by HeedfulCrayon** [comment]
@Snacker001 I am using it in the Home Assistant add-on and I am using the native yaml automations:
```
id: 'google_assistant_relay_heartbeat'
alias: Google Assistant Relay Heartbeat
description: 'Keeps the token for Google Assistant Relay Alive'
trigger:
  platform: time
  at:
    - "09:30:00"
    - "12:00:00"
    - "18:00:00"
    - "00:00:00"
    - "06:00:00"
action:
  - service: rest_command.assistant_relay
    data:
      command: What time is it?
```

**Comment by ryancasler** [comment]
Don't think this is a GAR problem. I am not seeing any problem running in Docker on Ubuntu. It can be days between broadcasts and I'm not having any problems.

**Comment by mbaluda** [comment]
I see the same behavior

**Comment by peterolby** [comment]
I'm having the same issue. Have not been tracking but would guess I loose grant after about 4 days.
Will set up automation to track this more closely.

**Comment by HeedfulCrayon** [comment]
Mine finally died.  Looks like running an automation periodically doesn't seem to fix the issue

**Comment by wolfet410** [comment]
I ran into the same problem twice now, it does not appear to be related to lack of activity. I'm posting in case my experiences help narrow down the problem.

The first failure, my Pi lost power hard and didn't boot back up properly. After solving the boot problem, I still received the invalid_grant errors. I didn't do any other testing, I reloaded the OS on the Pi and started over.

The second time, last night, I was actively sending commands when the credentials began failing. I sent 475 commands in 1 day successfully and began receiving the invalid_grant error on the 476th command. 

The Google Assistant API reported "1 of 1 quota is reaching limit", the quota is 500 requests per day so I was near it.

I confirmed Google reported the Assistant API quota reset overnight, but I was still getting the same invalid_grant response this morning. I created a new Assistant-Relay user with no other issues to temporarily mitigate the problem.

**Comment by ryancasler** [comment]
What environment are you running GAR in?  I am running in a plain Linux Alpine based Docker container and I am not having this problem.  I would look more at what your  OS might be contributing to this.  If it was a GAR problem, we would all be seeing it.

**Comment by jayhohoho2019** [comment]
I've been having the same issues.  I thought it was occurring every 7 days for me (Sunday to Sunday) but I lost it again today after really 2 day, after I had also set up another webCoRE piston to ping every 5 hours.  I'm on a Ubuntu vm on vmware running on a Windows 10 host.  And I don't think I would have hit the 500 requests per day limit.  This is getting really annoying.

**Comment by Snacker001** [comment]
Has this problem a few times when deploying AR via the Hassio add-on. Since moving it to run on a VM running ubuntu18.04 it has not reoccurred. 

For what it's worth I have a benign automation running every 5 hours, but I am not sure that really helps - it certainly didn't when running the hassio add-on. I am also nowhere near the 500 per day request rate.

**Comment by wolfet410** [comment]
I do not think the problem is only caused by exceeding the quota. 

Just speculation, but it seems once the invalid_grant error appear for whatever different reason it does not recover until a new user is created. Even if the root cause of the invalid_grant error gets solved (i.e. timeout no longer occurs, quota has expired, etc) that user won't stop reporting a failure. Problems like timeouts or disconnects that occur for reasons completely unrelated to GAR, and would normally be solved by sending another request, ultimately stop the service until manual intervention.

If that's the case, I agree a more powerful server would have less of a chance of initial failure avoiding this issue altogether.

**Comment by FaberOptime** [comment]
I too am encountering this issue.
GAR v3.2.0 running on Win10.

**Comment by littlbee** [comment]
Solved for me when using an automation to ask the time (no broadcast) every 6 hours, using Hass.io. At least it's been running for more than a week as such.

**Comment by HeedfulCrayon** [comment]
> Solved for me when using an automation to ask the time (no broadcast) every 6 hours, using Hass.io. At least it's been running for more than a week as such.

This is exactly what I did, but it still ended up failing after a while

**Comment by littlbee** [comment]
Well... Seems I spoke too fast... It finally broke today. Last execution was at 12h00, then at 6pm got the invalid grand issue again. I think I'm going to back using the Google Assistant Webserver add-on on hass.io...

**Comment by Snacker001** [comment]
@littlbee hope GAW works for you, it was because that seemed to stop working for me that I migrated to GAR! Since I moved from the add-on to running directly on ubuntu (VM) a week ago I've had no more problems with GAR, fingers crossed ....

**Comment by matteskonto** [comment]
Now I had to reenable my accounts again to be able to use Relay. The permission disappears from the Google account but the same secrets can be used to reenable the service so the OAuth is still vaild.

I still think this has to do with the testing function that is used and limited that are placed upon this environment. 

When I create a credential according to the guide, this message appear:

![image](https://user-images.githubusercontent.com/26691679/105624380-87310300-5e21-11eb-837f-5a9a11741da7.png)

I am not sure what "Sensitive scope login" means but maybe it is a new login for every time HA is restarted (I use the Add-on) which can explain why the Add-on is experiencing this issue more frequently than the stand-alone version that is probably not restarted that often. Also explains why both my accounts fail at the same time even though they are used very differently.

**Comment by ryancasler** [comment]
All you have to do is set up the user consent screen.  There is nothing special needed to do that.  Just click on the hamburger menu on the upper left corner of the Google Developers console then click APIs and Services then Oauth Consent Screen.  
![image](https://user-images.githubusercontent.com/30270489/105641305-32a57c00-5e51-11eb-9e3e-996b894f75ce.png)

The only thing you should have to fill in is the App name and the support email at the top.  Nothing else should need to be filled in.

**Comment by matteskonto** [comment]
I have set up a consent screen, I think this is required to get GAR to work, but the consent screen is not verified by Google and it will never be because it is not a "real" project.

Don't you get the same notice when you create a new OAuth client?

**Comment by Snacker001** [comment]
So I spoke too soon, it has just failed again for me. Fixed by deleting the user and then adding a new one, same name, same client_secret file then all back up and working again. I guess until fixed I will be doing this weekly

**Comment by ryancasler** [comment]
Mine is verified.  It doesn't have to be a commercial project to be verified by Google.

**Comment by matteskonto** [comment]
My consent screen is set up but not verified and thus I get the 100 sensitive scope logins restriction. Do you also get that message when creating a new OAuth client?

**Comment by peterolby** [comment]
> My consent screen is set up but not verified and thus I get the 100 sensitive scope logins restriction. Do you also get that message when creating a new OAuth client?

I get the same message.

**Comment by jayhohoho2019** [comment]
Fyi yesterday after I published the app (so its status became In Production) in the developer console, I also got the new verification status which is Verification Not Required.    After that when I added a new user, I no longer got the Unverified App warning.  Will update here in a week where the invalid_grant error returns.

**Comment by matteskonto** [comment]
I had to redo my grants again even with Verification not required status. But I still get the same information when I create a new OAuth client that it is 100 sensetive logins because the consent is not verified...

**Comment by jayhohoho2019** [comment]
Update.  Still working for me after 8+ days.  It always expired in 7 days or sooner before.  What I did was I published the app in the developer console (status showing In Production).  Verification status is Verification Not Required.  I didn't get the Unverified App warning after this, when I added a new user.

**Comment by jayhohoho2019** [comment]
Update.  So it's been 15+ days for me and still works (no invalid_grant error).  Anybody else successful in reproducing what I did?

**Comment by jesselumarie** [comment]
I’m trying, but only two days in. Will post if I’m still good after a week.

**Comment by Snacker001** [comment]
> Update. So it's been 15+ days for me and still works (no invalid_grant error). Anybody else successful in reproducing what I did?

I "published" 4 days ago and fine so far. Mine typically failed after a week, so still unproven for me but fingers crossed!

**Comment by Snacker001** [comment]
So by way of update, a week on and having published on the developer console it has fallen over again. A quick remove and re-add user with the same client_secret and back up.

Interestingly, I also have a similar issue with Nest, again on almost a weekly basis it fails and needs re-authenticating via the integrations pain. Looking into that it seems there are issues where google invalidates the tokens:

[https://github.com/home-assistant/core/issues/44584]

[https://developers.google.com/identity/protocols/oauth2#expiration](url)

**Comment by ryancasler** [comment]
How many users do you have set up for the project?  I only have one and I have never had this problem.  I just use the same Oauth client everywhere (since they are all me).

**Comment by Snacker001** [comment]
Only 1 user for me too and GAR probably only triggers commands around 10 times a day, so should be nowhere near quotas

**Comment by matteskonto** [comment]
I have it running now for 10 days without issue after I made the apps in Production status for two users (one project each)

**Comment by jayhohoho2019** [comment]
Did you get an unverified app message from Google when adding the user?

**Comment by matteskonto** [comment]
Not anymore, I still get the 100 logins limit when creating a new OAuth client

**Comment by jesselumarie** [comment]
mine still seems to be working too (it was off for a few days, as my kid apparently unplugged my raspberry pi 😅), but after starting up the server again it's working without having to redo my credentials.

**Comment by craigmcgowan** [comment]
Getting the same issue, thankfully resolved by resetting my user as suggested above. Look forward to a full time fix

**Comment by jayhohoho2019** [comment]
You are still getting this issue even after publishing the app?

**Comment by craigmcgowan** [comment]
Ill try that. I had thought that I saw a comment saying it didnt work so I never tried it. Have just published it now.
Thank you

**Comment by Snacker001** [comment]
At the risk of tempting fate, 11 days on and still working. In case it makes any difference this is the first time it has been "reactivated" post publishing the app, rather than publishing it after authenticating last time. Fingers crossed

**Comment by jesselumarie** [comment]
Mine is still working, nearly two weeks after publishing

**Comment by Snacker001** [comment]
why oh why did I post an update?! Failed this morning and requires a reset again ....

**Comment by pickonedev** [comment]
> solved

This addon was not updated for almost half of Year... What can you ask more to work? Nothing! The addon it is almost dead...

**Comment by henning334** [comment]
> So by way of update, a week on and having published on the developer console it has fallen over again. A quick remove and re-add user with the same client_secret and back up.
> 
> Interestingly, I also have a similar issue with Nest, again on almost a weekly basis it fails and needs re-authenticating via the integrations pain. Looking into that it seems there are issues where google invalidates the tokens:
> 
> [https://github.com/home-assistant/core/issues/44584](url)
> 
> [https://developers.google.com/identity/protocols/oauth2#expiration](url)

Is it still working for you after publishing it again?

I'm pretty new to GAR, and noticed in the last few days that it stopped working. Found i get the same error "UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant" as you guys are.

Will try to publish the app, but i'm not certain thats a permanent fix.
If it is, i suggest install guides/instructions are updated with this info.

**Comment by jonathanbower** [comment]
Publishing the app is not a solution. Mine just failed after about three weeks.

**Comment by Snacker001** [comment]
Mine is still working fine post publishing 20 days ago.

**Comment by craigmcgowan** [comment]
Mine has failed since publishing 9 days ago too.

**Comment by ryancasler** [comment]
Yours has failed or has not failed? 

I'm pretty sure I said that pushing to production was the solution back in January if I'm not mistaken.  I have screenshots from the setup and I'll put a step-by-step together for the future.

**Comment by craigmcgowan** [comment]
Yes mine has failed. I published around 11 days ago.and already again I get the invalid grant error.

**Comment by jayhohoho2019** [comment]
Mine has been working since Jan 25th.  Here are my observations from a previous post:
_Fyi yesterday after I published the app (so its status became In Production) in the developer console, I also got the new verification status which is Verification Not Required. After that when I added a new user, I no longer got the Unverified App warning._ 

I think if you don't get the unverified app warning when you add a new user you should be fine.

**Comment by rocker01** [comment]
I've been facing this issue regularly too. Have v3.2.0 running on a Raspberry Pi 4 (4GB model), and after a few days I start getting this error message. The only solution to this has been to either reinstall Assistant Relay or remove and re-add my user.

I appreciate all the work that must have gone into creating this project, and it is honestly incredible - the only this that is keeping it from greatness is this annoying bug!

**Comment by drinfernoo** [comment]
I can confirm I'm also seeing this same behavior in 3.2.0:
```bash
/root/.pm2/logs/www-error.log last 15 lines:
0|www      |   details: 'Getting metadata from plugin failed with error: invalid_grant'
0|www      | }
0|www      | Auth error:Error: invalid_grant
0|www      | Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant
0|www      |     at Object.exports.createStatusError (/assistant_relay/node_modules/grpc/src/common.js:91:15)
0|www      |     at ClientDuplexStream._emitStatusIfDone (/assistant_relay/node_modules/grpc/src/client.js:233:26)
0|www      |     at ClientDuplexStream._receiveStatus (/assistant_relay/node_modules/grpc/src/client.js:211:8)
0|www      |     at Object.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www      |     at InterceptingListener._callNext (/assistant_relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www      |     at InterceptingListener.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www      |     at /assistant_relay/node_modules/grpc/src/client_interceptors.js:1127:18 {
0|www      |   code: 14,
0|www      |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|www      |   details: 'Getting metadata from plugin failed with error: invalid_grant'
0|www      | }
```
This happens after a few days, and when I try to broadcast (via an HA automation), I still get the "broadcast chime" noise playing, but then nothing is spoken. Deleting the user and re-adding it (even with the same credentials) does seem to work for awhile, as others have said.

**Comment by lazdavila** [comment]
> Update. Still working for me after 8+ days. It always expired in 7 days or sooner before. What I did was I published the app in the developer console (status showing In Production). Verification status is Verification Not Required. I didn't get the Unverified App warning after this, when I added a new user. Notice this: if your users are seeing the "unverified app" screen , it is because your OAuth request includes additional scopes that haven't been approved.

... just in case anyone else is also having problems figuring out how to 'publish' the app (took me ages to find it), it is under: https://console.cloud.google.com/apis/credentials/consent, in the "Publishing Status" section. After doing this, I also removed and re-added the user in the relay site, and confirmed that I did not get the "Unverified App" warning.

**Comment by dotrooster** [comment]
I wasn't sure if I should start a new thread or just tack onto this one since my issue is related. Sorry if I'm in the wrong place.

I've been having the same invalid_grant issue as everyone else, but when I try to publish the app and then re-create the user in RA, I get an "Error 400: invalid_request: message where I should be seeing an option to login to my google account. Specifically, the probelm is apparently with "redirect_uri: urn:ietf:wg:oauth:2.0:oob". Anyone know where I'm going wrong?

Thanks!

**Comment by techtom609** [comment]
> I wasn't sure if I should start a new thread or just tack onto this one since my issue is related. Sorry if I'm in the wrong place.
> 
> I've been having the same invalid_grant issue as everyone else, but when I try to publish the app and then re-create the user in RA, I get an "Error 400: invalid_request: message where I should be seeing an option to login to my google account. Specifically, the probelm is apparently with "redirect_uri: urn:ietf:wg:oauth:2.0:oob". Anyone know where I'm going wrong?
> 
> Thanks!

Im running into this same exact issue. I have tried absolutely everything but cannot get passed this error. Any ideas?

**Comment by jiffyjaff** [comment]
Your issue is the same as what I've reported here. 

https://github.com/greghesp/assistant-relay/issues/266

**Comment by techtom609** [comment]
Thank you so much for the update!!
